### ISSUE TITLE
Fails to build with ghc-8.4.3

### ISSUE THREAD

**Issue by iliastsi** [byorgey/BlogLiterately#40]
Fails to build with ghc-8.4.3 with the following error:

```
src/Text/BlogLiterately/Options.hs:136:10: error:
    * No instance for (Semigroup BlogLiterately)
        arising from the superclasses of an instance declaration                                     
    * In the instance declaration for `Monoid BlogLiterately'
    |
136 | instance Monoid BlogLiterately where                                                           
    |          ^^^^^^^^^^^^^^^^^^^^^                                                                 
```

**Comment by byorgey** [comment]
Fixed in @d2c9305 , new Hackage release coming soon.

**Comment by byorgey** [comment]
Released `BlogLiterately-0.8.6.3` to Hackage.
