### ISSUE TITLE
pandoc 2.2

### ISSUE THREAD

**Issue by clinty** [byorgey/BlogLiterately#39]
Please update for pandoc 2.2

**Comment by byorgey** [comment]
Hi there, thanks for the report.  I'm working on it but it looks like it is also going to require some `HaXmL` updates, and not sure how long that will be.

**Comment by byorgey** [comment]
Just to record some progress, it is now possible to build HEAD `BlogLiterately` with `pandoc-2.2` under GHC-8.2 (not 8.4 since `HaXml` does not compile, even with `--allow-newer`), but this results in the following errors:

```
[10 of 12] Compiling Text.BlogLiterately.Transform ( src/Text/BlogLiterately/Transform.hs, dist/dist-sandbox-afe275d3/build/Text/BlogLiterately/Transform.o )

src/Text/BlogLiterately/Transform.hs:587:42: error:
    Data constructor not in scope:
      LaTeXMathML :: Maybe [Char] -> HTMLMathMethod
    |
587 |         opt `isPrefixOf` "asciimathml" = LaTeXMathML (mathUrlMaybe opt)
    |                                          ^^^^^^^^^^^

src/Text/BlogLiterately/Transform.hs:592:42: error:
    • Data constructor not in scope:
        JsMath :: Maybe [Char] -> HTMLMathMethod
    • Perhaps you meant ‘Math’ (imported from Text.Pandoc)
    |
592 |       | opt `isPrefixOf` "jsmath"      = JsMath (mathUrlMaybe opt)
    |                                          ^^^^^^
```
I need to look into what changed in pandoc and how to update.

**Comment by clinty** [comment]
Maybe https://github.com/jgm/pandoc/issues/4607 is helpful?

**Comment by byorgey** [comment]
@clinty Huh?  I don't see how that ticket about `--gladtex` is relevant.

**Comment by byorgey** [comment]
Oh, I see, https://github.com/jgm/pandoc/commit/16f36eee43c9401612aa647eff4f041c4270e969 .  So all we have to do is remove those options.

**Comment by byorgey** [comment]
Uploaded `BlogLiterately-0.8.6.2` to Hackage which should work with GHC 8.4 and pandoc 2.2.  Let me know if you have any issues!
